# [Config Server 의 목적]
# [Config Server 가 Git 저장소에서 설정을 읽어 각 마이크로 서비스(product-service, order-service)에 설정 정보를 제공

#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
# [가동 순서]
# Config Server > Eureka > 마이크로 서비스들 > Gateway 순으로 가동.
#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

server:
  port: 8881

spring:
  application:
    name: config-server   # 이 애플리케이션의 이름을 정하기. (!중요함! - yml 파일 매핑 규칙에 이름이 쓰임)

  # GitHub 정보
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qwer1324897/config-repo.git
          default-label: main
          username: qwer1324897
          password: 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

          clone-on-start: true    # 서버 가동 시 즉시 git clone
          force-pull: true  # 매번 pull 을 강제하겠다 라는 뜻. (변경 설정을 반영하기 위해)

management:
  endpoints:
    web:
      exposure:
        include: health,info